package logger

// 中文（简体，sc）对照表。键与 catalog_tc.go 的繁体那份**必须完全一致**，
// 由 TestCatalogsAreInSync 守住：差一个键就会出现「繁体翻得出、简体留英文」这种诡异现象。
// 用词不是繁转简就完事：缓存／地址／证书／端口／网络／数据路径／程序 这些是大陆习惯说法，
// 所以先生成字形、再整批覆盖术语。要加讯息时**两份都要加**，漏一份测试就会红。

var messagesSc = map[string]string{
	"Connectivity Check Failed":        "节点健康检查没过",
	"Connectivity Check":               "节点健康检查",
	"Skip check due to no DNS record.": "这个节点目前没有可用的解析结果，这次检查先跳过",
	"[ALIVE --tcp4-> NOT ALIVE]":       "节点转为不通（tcp4）",
	"[ALIVE --tcp6-> NOT ALIVE]":       "节点转为不通（tcp6）",
	"[ALIVE --udp4-> NOT ALIVE]":       "节点转为不通（udp4）",
	"[ALIVE --udp6-> NOT ALIVE]":       "节点转为不通（udp6）",
	"[ALIVE --udp4(DNS)-> NOT ALIVE]":  "节点查 DNS 转为不通（udp4）",
	"[ALIVE --udp6(DNS)-> NOT ALIVE]":  "节点查 DNS 转为不通（udp6）",
	"[NOT ALIVE --tcp4-> ALIVE]":       "节点恢复可用（tcp4）",
	"[NOT ALIVE --tcp6-> ALIVE]":       "节点恢复可用（tcp6）",
	"[NOT ALIVE --udp4-> ALIVE]":       "节点恢复可用（udp4）",
	"[NOT ALIVE --udp6-> ALIVE]":       "节点恢复可用（udp6）",
	"[NOT ALIVE --udp4(DNS)-> ALIVE]":  "节点查 DNS 恢复可用（udp4）",
	"[NOT ALIVE --udp6(DNS)-> ALIVE]":  "节点查 DNS 恢复可用（udp6）",
	"TCP relay completed":              "TCP 中转结束",
	"Group has no dialer alive":        "这个分组已经没有可用节点",
	"The number of dialers is 0":       "一条节点都没有",
	"dae is running":                   "dae 已启动",
	"start process successfully":       "启动完成",
}

var messagePrefixesSc = map[string]string{
	"[StickyIP] Check cycle incremented":                                         "固定出口 IP：检查周期递进 ",
	"[StickyIP] No cache entry found":                                            "固定出口 IP：没有缓存可查（第一次连这个地址） ",
	"[StickyIP] DialContext called":                                              "固定出口 IP：要连线了 ",
	"[StickyIP] Trying proxy IP":                                                 "固定出口 IP：改用记下来的那个地址 ",
	"[StickyIP] No valid cached IP - resolving proxy domain":                     "固定出口 IP：缓存的地址不能用，重新查域名 ",
	"[StickyIP] Resolved proxy domain to IPs":                                    "固定出口 IP：域名查到了 ",
	"[StickyIP] Successfully connected to proxy IP":                              "固定出口 IP：连线成功 ",
	"[StickyIP] All proxy IPs failed":                                            "固定出口 IP：记下的地址全部连不上 ",
	"[StickyIP] Failed to connect to proxy IP (will try next)":                   "固定出口 IP：这个地址连不上，换下一个 ",
	"[StickyIP] Cached IP failed - invalidating and re-resolving":                "固定出口 IP：记下的地址坏了，作废重查 ",
	"[StickyIP] Cache entry expired":                                             "固定出口 IP：缓存过期 ",
	"[StickyIP] Cache is nil":                                                    "固定出口 IP：还没有缓存 ",
	"[StickyIP] Cycle mismatch - cache not from current cycle":                   "固定出口 IP：缓存是上个周期的，作废 ",
	"[StickyIP] Cache hit - returning cached IP":                                 "固定出口 IP：缓存命中，直接沿用 ",
	"[StickyIP] Cache hit - using cached proxy IP":                               "固定出口 IP：沿用记下来的地址 ",
	"[StickyIP] Cached proxy IP":                                                 "固定出口 IP：已记下地址 ",
	"[StickyIP] No cached IP for this network type and IP version":               "固定出口 IP：这个网络类型还没有记下的地址 ",
	"[StickyIP] DNS resolution failed (will use original domain)":                "固定出口 IP：域名查不到，改用原本的方式 ",
	"[StickyIP] Direct dial (already an IP)":                                     "固定出口 IP：目标本身就是地址，不用查 ",
	"[StickyIP] Pass-through (not proxy address)":                                "固定出口 IP：这不是代理地址，原样放行 ",
	"[StickyIP] Invalidated cache for protocol+IP version":                       "固定出口 IP：作废该协议＋地址类型的缓存 ",
	"[StickyIP] Protocol cache invalidated due to connection failure":            "固定出口 IP：连线失败，作废该协议缓存 ",
	"[StickyIP] Protocol+IP version cache invalidated due to connection failure": "固定出口 IP：连线失败，作废该协议＋地址类型缓存 ",
	"[StickyIP] NewStickyIpDialer created":                                       "固定出口 IP：建立好包装器 ",
	"[DialerRegister] Checking if sticky IP caching is needed":                   "节点注册：先看这条要不要固定出口 IP ",
	"[DialerRegister] Creating sticky IP dialer wrapper for proxy domain":        "节点注册：为这个域名建立固定出口 IP包装 ",
	"[DialerRegister] Proxy is IP address - no sticky IP caching needed":         "节点注册：代理本身就是地址，不需要固定出口 IP ",
	"StickyIP: Check cycle incremented":                                          "固定出口 IP：检查周期递进 ",
	"StickyIP: No cache entry found":                                             "固定出口 IP：没有缓存可查（第一次连这个地址） ",
	"StickyIP: DialContext called":                                               "固定出口 IP：要连线了 ",
	"StickyIP: Trying proxy IP":                                                  "固定出口 IP：改用记下来的那个地址 ",
	"StickyIP: No valid cached IP - resolving proxy domain":                      "固定出口 IP：缓存的地址不能用，重新查域名 ",
	"StickyIP: Resolved proxy domain to IPs":                                     "固定出口 IP：域名查到了 ",
	"StickyIP: Successfully connected to proxy IP":                               "固定出口 IP：连线成功 ",
	"StickyIP: Cycle mismatch - cache not from current cycle":                    "固定出口 IP：缓存是上个周期的，作废 ",
	"StickyIP: Cache hit - returning cached IP":                                  "固定出口 IP：缓存命中，直接沿用 ",
	"StickyIP: Cache hit - using cached proxy IP":                                "固定出口 IP：沿用记下来的地址 ",
	"StickyIP: Cached proxy IP":                                                  "固定出口 IP：已记下地址 ",
	"StickyIP: NewStickyIpDialer created":                                        "固定出口 IP：建立好包装器 ",
	"DialerRegister: Checking if sticky IP caching is needed":                    "节点注册：先看这条要不要固定出口 IP ",
	"DialerRegister: Creating sticky IP dialer wrapper for proxy domain":         "节点注册：为这个域名建立固定出口 IP包装 ",
	"Suppressing dialer availability failure during reload handoff":              "重载交接中，这次的失败先不算节点坏",
	"CRITICAL: the conn-state maps are rejecting flows continuously":             "严重：连线状态表已经持续挡掉新连线 ",
	"datapath resource exhaustion or event loss in this interval":                "这区间有资源耗尽或事件遗失 ",
	"datapath counters with no per-event warning advanced in this interval":      "这区间有些数据路径计数器有增加（不会单独告警的那种） ",
	"Group ": "分组 ",
	"Recovery confirmed: long-term stability detected":              "已确认节点稳定，重试退减档位调低 ",
	"Recovery detection initialized":                                "已启动「节点恢复侦测」",
	"cleanupRoutingHandoffMap: removed":                             "清掉重载交接表的过期条目：",
	"Skip TCP relay eBPF offload":                                   "跳过 TCP 中转的 eBPF 卸载（offload）：",
	"Rewrite dial target":                                           "改写连线目标",
	"Group selects dialer":                                          "分组选中节点",
	"Group re-selects dialer":                                       "分组换了节点",
	"Group's check option has been override.":                       "这个分组的健康检查目标已覆盖（各组独立判定）",
	"dialer connectivity check is sleeping due":                     "节点检查暂停中，原因：",
	"cleanupConnStateMap: removed":                                  "清掉过期连线记录：",
	"NotifyLatencyChange: ignoring stale availability notification": "忽略一则过期的可用性通知",
	"Read geosite":                                                  "读取域名清单",
	"Read geoip":                                                    "读取地址清单",
	"cache hit":                                                     "DNS 缓存命中",
	"Connectivity Check failed":                                     "节点健康检查没过",
	"Failed to connect to the dialer":                               "连不上这条节点",
	"failed to dial":                                                "拨号失败：",
	"[Reload]":                                                      "〔重载〕",
}

var errsSc = map[string]string{
	"no applicable IP for this network type": "这个网络类型（v4／v6）没有可用地址",
	"network is unreachable":                 "没有路由可以到这个网络（通常是 v6 没起来）",
	"connection refused":                     "对方直接拒绝连线",
	"no such host":                           "域名解析不到",
	"i/o timeout":                            "等回应等到逾时",
	"context deadline exceeded":              "等太久被取消",
	"context canceled":                       "连线被取消",
	"operation was canceled":                 "操作被取消",
	"tls: failed to verify certificate":      "证书验证不过",
	"tls: handshake failure":                 "TLS 握手失败",
	"bad file descriptor":                    "文件描述符已失效（程序正在收尾）",
	"permission denied":                      "权限不足",
	"address already in use":                 "端口已被占用",
}

var errPrefixesSc = map[string]string{
	"Head \"":  "对 HEAD 请求没回应：",
	"Get \"":   "对 GET 请求没回应：",
	"dial tcp": "拨号失败 ",
	"dial udp": "UDP 拨号失败 ",
}
